-- ============================================================
-- ENRIQUECIMIENTO ELENCO TMDB — generado por enriquecer_elenco.py
-- ============================================================

BEGIN;

-- Asegurar que existen las tablas necesarias
CREATE TABLE IF NOT EXISTS PERSONA (
  persona_id SERIAL PRIMARY KEY,
  nombre VARCHAR(200) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS PELICULA_PERSONA (
  pelicula_id INT REFERENCES PELICULA(pelicula_id),
  persona_id  INT REFERENCES PERSONA(persona_id),
  rol         VARCHAR(50) NOT NULL,
  UNIQUE(pelicula_id, persona_id, rol)
);

INSERT INTO PERSONA (nombre) VALUES ('Travis Knight') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 139, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Travis Knight' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Nicholas Galitzine') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 139, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Nicholas Galitzine' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Camila Mendes') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 139, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Camila Mendes' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Idris Elba') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 139, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Idris Elba' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jared Leto') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 139, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jared Leto' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Alison Brie') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 139, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Alison Brie' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jóhannes Haukur Jóhannesson') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 139, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jóhannes Haukur Jóhannesson' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Kane Parsons') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 129, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Kane Parsons' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Chiwetel Ejiofor') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 129, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Chiwetel Ejiofor' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Renate Reinsve') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 129, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Renate Reinsve' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Finn Bennett') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 129, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Finn Bennett' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Lukita Maxwell') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 129, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Lukita Maxwell' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Mark Duplass') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 129, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Mark Duplass' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Avan Jogia') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 129, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Avan Jogia' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Fernando Barreda Luna') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 171, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Fernando Barreda Luna' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Tessa Ía') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 171, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Tessa Ía' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Mauricio Isaac') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 171, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Mauricio Isaac' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Leo Deluglio') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 171, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Leo Deluglio' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Hernán del Riego') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 171, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Hernán del Riego' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Daniel Roher') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 141, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Daniel Roher' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Leo Woodall') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 141, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Leo Woodall' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Havana Rose Liu') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 141, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Havana Rose Liu' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Dustin Hoffman') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 141, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Dustin Hoffman' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('ליאור רז') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 141, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'ליאור רז' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Tovah Feldshuh') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 141, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Tovah Feldshuh' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jean Reno') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 141, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jean Reno' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Mike Johnson') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 42, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Mike Johnson' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Johnny Depp') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 42, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Johnny Depp' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Helena Bonham Carter') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 42, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Helena Bonham Carter' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Emily Watson') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 42, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Emily Watson' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Tracey Ullman') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 42, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Tracey Ullman' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Paul Whitehouse') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 42, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Paul Whitehouse' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Joanna Lumley') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 42, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Joanna Lumley' ON CONFLICT DO NOTHING;

UPDATE PELICULA SET sinopsis = 'Bajo presión sigue al general Dwight D. Eisenhower y al capitán James Stagg mientras enfrentan una decisión imposible: lanzar la invasión marítima más grande y peligrosa de la historia o arriesgarse a perder la guerra por completo.' WHERE pelicula_id = 289;
INSERT INTO PERSONA (nombre) VALUES ('Anthony Maras') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 289, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Anthony Maras' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Andrew Scott') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 289, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Andrew Scott' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Brendan Fraser') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 289, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Brendan Fraser' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Kerry Condon') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 289, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Kerry Condon' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Chris Messina') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 289, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Chris Messina' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Damian Lewis') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 289, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Damian Lewis' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Tamsin Topolski') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 289, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Tamsin Topolski' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Steven Spielberg') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 127, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Steven Spielberg' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Emily Blunt') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 127, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Emily Blunt' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Josh O''Connor') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 127, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Josh O''Connor' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Colin Firth') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 127, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Colin Firth' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Colman Domingo') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 127, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Colman Domingo' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Eve Hewson') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 127, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Eve Hewson' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Wyatt Russell') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 127, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Wyatt Russell' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('David Frankel') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 142, persona_id, 'Director' FROM PERSONA WHERE nombre = 'David Frankel' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Anne Hathaway') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 142, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Anne Hathaway' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Meryl Streep') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 142, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Meryl Streep' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Emily Blunt') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 142, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Emily Blunt' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Stanley Tucci') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 142, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Stanley Tucci' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Kenneth Branagh') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 142, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Kenneth Branagh' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Justin Theroux') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 142, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Justin Theroux' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('David Pablos') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 276, persona_id, 'Director' FROM PERSONA WHERE nombre = 'David Pablos' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Víctor Prieto') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 276, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Víctor Prieto' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Osvaldo Sánchez') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 276, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Osvaldo Sánchez' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Mariano López Sosa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 276, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Mariano López Sosa' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Héctor Cárdenas') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 276, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Héctor Cárdenas' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Obdulia Morales') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 276, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Obdulia Morales' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Elizabeth Infante') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 276, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Elizabeth Infante' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Roberto Girault') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 144, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Roberto Girault' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Sandra Echeverría') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 144, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Sandra Echeverría' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Michel Brown') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 144, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Michel Brown' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Mariané Cartas') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 144, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Mariané Cartas' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Fernando Cattori') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 144, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Fernando Cattori' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Mauricio Barrientos') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 144, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Mauricio Barrientos' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Diego Guzmán') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 144, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Diego Guzmán' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Hanna Bergholm') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 175, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Hanna Bergholm' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Rupert Grint') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 175, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Rupert Grint' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Seidi Haarla') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 175, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Seidi Haarla' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Pamela Tola') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 175, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Pamela Tola' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Pirkko Saisio') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 175, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Pirkko Saisio' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Rebecca Lacey') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 175, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Rebecca Lacey' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('John Thomson') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 175, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'John Thomson' ON CONFLICT DO NOTHING;

UPDATE PELICULA SET sinopsis = 'Henry Spencer, un joven depresivo y asustadizo, sufre desde pequeño unas extrañas pesadillas de las que intenta liberarse a través de su imaginación. Un día, su amiga Mary lo invita a cenar a casa; se entera entonces de que ha sido padre de un bebé prematuro e inhumano. Mary y el extraño bebé se instalan en casa de Henry, donde un escenario iluminado tras el radiador muestra la presencia de una mujer.' WHERE pelicula_id = 288;
INSERT INTO PERSONA (nombre) VALUES ('David Lynch') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 288, persona_id, 'Director' FROM PERSONA WHERE nombre = 'David Lynch' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jack Nance') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 288, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jack Nance' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Charlotte Stewart') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 288, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Charlotte Stewart' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Allen Joseph') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 288, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Allen Joseph' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jeanne Bates') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 288, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jeanne Bates' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Judith Roberts') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 288, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Judith Roberts' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Laurel Near') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 288, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Laurel Near' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Sébastien Vaniček') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 178, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Sébastien Vaniček' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Souheila Yacoub') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 178, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Souheila Yacoub' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Tandi Wright') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 178, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Tandi Wright' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Hunter Doohan') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 178, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Hunter Doohan' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Luciane Buchanan') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 178, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Luciane Buchanan' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Erroll Shand') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 178, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Erroll Shand' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Maude Davey') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 178, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Maude Davey' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Adam Stein') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 155, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Adam Stein' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Kaitlyn Santa Juana') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 155, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Kaitlyn Santa Juana' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Teo Briones') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 155, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Teo Briones' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Rya Kihlstedt') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 155, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Rya Kihlstedt' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Richard Harmon') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 155, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Richard Harmon' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Owen Patrick Joyner') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 155, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Owen Patrick Joyner' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Anna Lore') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 155, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Anna Lore' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Emma Tammi') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 44, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Emma Tammi' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Josh Hutcherson') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 44, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Josh Hutcherson' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Piper Rubio') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 44, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Piper Rubio' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Elizabeth Lail') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 44, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Elizabeth Lail' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Matthew Lillard') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 44, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Matthew Lillard' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Freddy Carter') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 44, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Freddy Carter' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Wayne Knight') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 44, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Wayne Knight' ON CONFLICT DO NOTHING;

UPDATE PELICULA SET sinopsis = 'La vida de Manuel da un vuelco cuando Esmeralda, su amor perdido de hace quince años, lo llama inesperadamente. A pesar de estar a punto de casarse con otra persona, él se reencontrará con Esmeralda y ambos se darán cuenta de que su amor trasciende el tiempo.' WHERE pelicula_id = 283;
INSERT INTO PERSONA (nombre) VALUES ('Emiliano Castro Vizcarra') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 283, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Emiliano Castro Vizcarra' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Mauricio Ochmann') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 283, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Mauricio Ochmann' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Aislinn Derbez') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 283, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Aislinn Derbez' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Daniel Pérez Prada') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 283, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Daniel Pérez Prada' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Melina Figueroa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 283, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Melina Figueroa' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Miguel Ángel Jiménez') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 283, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Miguel Ángel Jiménez' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Eduardo Santacruz') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 283, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Eduardo Santacruz' ON CONFLICT DO NOTHING;

UPDATE PELICULA SET sinopsis = 'Un grupo de pasajeros internacionales en ruta de Los Ángeles a Shanghai se ven obligados a realizar un aterrizaje de emergencia en aguas infestadas de tiburones. Ahora deben superar el frenesí de los tiburones merodeantes.' WHERE pelicula_id = 299;
INSERT INTO PERSONA (nombre) VALUES ('Renny Harlin') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 299, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Renny Harlin' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Aaron Eckhart') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 299, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Aaron Eckhart' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Ben Kingsley') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 299, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Ben Kingsley' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Molly Belle Wright') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 299, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Molly Belle Wright' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Angus Sampson') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 299, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Angus Sampson' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Elijah Tamati') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 299, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Elijah Tamati' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Zhao Simei') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 299, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Zhao Simei' ON CONFLICT DO NOTHING;

UPDATE PELICULA SET sinopsis = 'Cuando Hana, una estudiante de medicina de primer año, se obsesiona con perder peso tras reencontrarse con una amiga que luce una transformación dramática, se ve arrastrada a un perturbador mundo de obsesión por la imagen corporal. Motivada por su interés amoroso, la influencer de fitness Alanya, para unirse a un programa de transformación extrema, Hana comienza a tomar las pastillas de dieta que su amiga le dio.' WHERE pelicula_id = 290;
INSERT INTO PERSONA (nombre) VALUES ('Natalie Erika James') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 290, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Natalie Erika James' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Midori Francis') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 290, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Midori Francis' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Danielle Macdonald') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 290, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Danielle Macdonald' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Madeleine Madden') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 290, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Madeleine Madden' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Joseph Baldwin') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 290, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Joseph Baldwin' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Robert Taylor') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 290, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Robert Taylor' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Emily Milledge') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 290, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Emily Milledge' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Jeff Tremaine') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 131, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Jeff Tremaine' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Johnny Knoxville') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 131, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Johnny Knoxville' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Steve-O') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 131, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Steve-O' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Chris Pontius') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 131, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Chris Pontius' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jason ''Wee Man'' Acuña') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 131, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jason ''Wee Man'' Acuña' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Dave England') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 131, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Dave England' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Preston Lacy') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 131, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Preston Lacy' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Ryan Adriandhy') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 69, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Ryan Adriandhy' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Prince Poetiray') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 69, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Prince Poetiray' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Quinn Salman') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 69, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Quinn Salman' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Graciella Abigail') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 69, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Graciella Abigail' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('M. Yusuf Ozkan') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 69, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'M. Yusuf Ozkan' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('M. Adhiyat') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 69, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'M. Adhiyat' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Angga Yunanda') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 69, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Angga Yunanda' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Ana Lorena Pérez Ríos') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 70, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Ana Lorena Pérez Ríos' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Omar Chaparro') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 70, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Omar Chaparro' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Mariana Calderón') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 70, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Mariana Calderón' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Natalia Reyes') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 70, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Natalia Reyes' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Gustavo Sánchez Parra') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 70, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Gustavo Sánchez Parra' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jorge A. Jimenez') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 70, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jorge A. Jimenez' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Sofía Álvarez') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 70, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Sofía Álvarez' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Paul Feig') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 68, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Paul Feig' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Sydney Sweeney') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 68, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Sydney Sweeney' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Amanda Seyfried') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 68, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Amanda Seyfried' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Brandon Sklenar') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 68, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Brandon Sklenar' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Michele Morrone') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 68, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Michele Morrone' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Indiana Elle') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 68, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Indiana Elle' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Elizabeth Perkins') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 68, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Elizabeth Perkins' ON CONFLICT DO NOTHING;

UPDATE PELICULA SET sinopsis = 'El matrimonio de Joe y Angela pende de un hilo. Cuando invitan a sus enigmáticos vecinos de arriba a una cena, la noche toma un rumbo inesperado.' WHERE pelicula_id = 202;
INSERT INTO PERSONA (nombre) VALUES ('Olivia Wilde') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 202, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Olivia Wilde' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Olivia Wilde') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 202, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Olivia Wilde' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Seth Rogen') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 202, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Seth Rogen' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Penélope Cruz') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 202, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Penélope Cruz' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Edward Norton') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 202, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Edward Norton' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Skip Howland') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 202, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Skip Howland' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Mel Powell') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 202, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Mel Powell' ON CONFLICT DO NOTHING;

UPDATE PELICULA SET sinopsis = 'Una cruda reinterpretación de la leyenda de Robin Hood donde un solitario marcado por la batalla, atormentado por su violento pasado, encuentra la redención a través de una mujer enigmática tras una grave herida.' WHERE pelicula_id = 291;
INSERT INTO PERSONA (nombre) VALUES ('Michael Sarnoski') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 291, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Michael Sarnoski' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Hugh Jackman') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 291, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Hugh Jackman' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jodie Comer') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 291, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jodie Comer' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Bill Skarsgård') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 291, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Bill Skarsgård' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Murray Bartlett') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 291, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Murray Bartlett' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Noah Jupe') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 291, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Noah Jupe' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jade Croot') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 291, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jade Croot' ON CONFLICT DO NOTHING;

UPDATE PELICULA SET sinopsis = 'Recrea la historia real del secuestro de 1977 que convirtió a Tony Kiritsis, un aspirante a empresario de Indianápolis, en un excéntrico héroe popular proscrito.' WHERE pelicula_id = 284;
INSERT INTO PERSONA (nombre) VALUES ('Gus Van Sant') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 284, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Gus Van Sant' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Bill Skarsgård') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 284, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Bill Skarsgård' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Dacre Montgomery') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 284, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Dacre Montgomery' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Cary Elwes') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 284, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Cary Elwes' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Myha''la') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 284, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Myha''la' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Colman Domingo') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 284, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Colman Domingo' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Al Pacino') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 284, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Al Pacino' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Christopher Nolan') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 137, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Christopher Nolan' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Matt Damon') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 137, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Matt Damon' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Tom Holland') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 137, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Tom Holland' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Anne Hathaway') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 137, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Anne Hathaway' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Robert Pattinson') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 137, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Robert Pattinson' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Himesh Patel') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 137, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Himesh Patel' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('John Leguizamo') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 137, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'John Leguizamo' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Adrian Chiarella') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 134, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Adrian Chiarella' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Joe Bird') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 134, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Joe Bird' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Stacy Clausen') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 134, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Stacy Clausen' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Mia Wasikowska') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 134, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Mia Wasikowska' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Nicholas Hope') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 134, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Nicholas Hope' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Tyallah Bullock') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 134, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Tyallah Bullock' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Ewen Leslie') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 134, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Ewen Leslie' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Julián Hernández') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 309, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Julián Hernández' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Luis Vegas') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 309, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Luis Vegas' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Axel Shuarma') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 309, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Axel Shuarma' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Angélica Baños Hernández') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 309, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Angélica Baños Hernández' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Tony Corrales') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 309, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Tony Corrales' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Luis Miguel Mata') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 309, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Luis Miguel Mata' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jere Caelum') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 309, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jere Caelum' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Lav Diaz') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 146, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Lav Diaz' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Gael García Bernal') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 146, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Gael García Bernal' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Amado Arjay Babon') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 146, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Amado Arjay Babon' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Ronnie Lazaro') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 146, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Ronnie Lazaro' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Ângela Ramos') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 146, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Ângela Ramos' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Dario Yazbek Bernal') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 146, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Dario Yazbek Bernal' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Tomás Alves') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 146, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Tomás Alves' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Allan Moyle') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 143, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Allan Moyle' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Flex Alexander') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 143, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Flex Alexander' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Krista Rae') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 143, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Krista Rae' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Eugene Clark') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 143, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Eugene Clark' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Peter Onorati') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 143, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Peter Onorati' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Lynne Cormack') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 143, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Lynne Cormack' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Brendan Prost') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 143, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Brendan Prost' ON CONFLICT DO NOTHING;

UPDATE PELICULA SET sinopsis = 'Esta es la historia alocada, ridícula y totalmente verídica de cómo los Minions conquistaron Hollywood, se convirtieron en estrellas de cine, lo perdieron todo, desataron monstruos en el mundo y luego se unieron para intentar salvar al planeta del caos que acababan de crear.' WHERE pelicula_id = 205;
INSERT INTO PERSONA (nombre) VALUES ('Pierre Coffin') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 205, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Pierre Coffin' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Pierre Coffin') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 205, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Pierre Coffin' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Trey Parker') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 205, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Trey Parker' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Allison Janney') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 205, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Allison Janney' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Christoph Waltz') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 205, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Christoph Waltz' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jeff Bridges') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 205, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jeff Bridges' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jesse Eisenberg') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 205, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jesse Eisenberg' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Pierre Coffin') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 136, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Pierre Coffin' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Pierre Coffin') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 136, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Pierre Coffin' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Trey Parker') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 136, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Trey Parker' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Allison Janney') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 136, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Allison Janney' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Christoph Waltz') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 136, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Christoph Waltz' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jeff Bridges') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 136, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jeff Bridges' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jesse Eisenberg') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 136, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jesse Eisenberg' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Albert Herman') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 159, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Albert Herman' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Mickey Rooney') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 159, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Mickey Rooney' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Delia Bogard') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 159, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Delia Bogard' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Billy Barty') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 159, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Billy Barty' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Kendall McComas') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 159, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Kendall McComas' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jimmy Robinson') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 159, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jimmy Robinson' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Marvin Stephens') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 159, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Marvin Stephens' ON CONFLICT DO NOTHING;

UPDATE PELICULA SET sinopsis = 'Moana que quiere ser una viajera marinera. Cuando su isla natal se ve amenazada, Moana debe adentrarse en el mar junto a un semidiós llamado Maui para salvar a su pueblo.' WHERE pelicula_id = 203;
INSERT INTO PERSONA (nombre) VALUES ('Thomas Kail') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 203, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Thomas Kail' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Catherine Lagaʻaia') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 203, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Catherine Lagaʻaia' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Dwayne Johnson') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 203, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Dwayne Johnson' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Rena Owen') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 203, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Rena Owen' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('John Tui') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 203, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'John Tui' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Frankie Adams') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 203, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Frankie Adams' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jemaine Clement') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 203, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jemaine Clement' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Fernando Eimbcke') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 176, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Fernando Eimbcke' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Bastián Escobar') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 176, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Bastián Escobar' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Teresa Sánchez') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 176, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Teresa Sánchez' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Hugo Ramirez') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 176, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Hugo Ramirez' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Enrique Arreola') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 176, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Enrique Arreola' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Curry Barker') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 128, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Curry Barker' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Michael Johnston') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 128, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Michael Johnston' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Inde Navarrette') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 128, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Inde Navarrette' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Cooper Tomlinson') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 128, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Cooper Tomlinson' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Megan Lawless') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 128, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Megan Lawless' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Andy Richter') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 128, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Andy Richter' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Haley Fitzgerald') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 128, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Haley Fitzgerald' ON CONFLICT DO NOTHING;

UPDATE PELICULA SET sinopsis = 'Cuando una fuerte tormenta deja a la patrulla canina varada en una isla inexplorada llena de dinosaurios vivos, los cachorros deben unirse a su nuevo aliado, Rex, para detener al alcalde Humdinger antes de que la codicia de este provoque una catastrófica erupción volcánica.' WHERE pelicula_id = 303;
INSERT INTO PERSONA (nombre) VALUES ('Cal Brunker') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 303, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Cal Brunker' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Carter Young') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 303, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Carter Young' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Hayden Chamberlen') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 303, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Hayden Chamberlen' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Mckenna Grace') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 303, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Mckenna Grace' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Rain Janjua') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 303, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Rain Janjua' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Henry Bolan') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 303, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Henry Bolan' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Lucien Duncan-Reid') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 303, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Lucien Duncan-Reid' ON CONFLICT DO NOTHING;

UPDATE PELICULA SET sinopsis = 'Más de doscientos años después de su muerte, Ripley vuelve a la vida gracias al empleo de técnicas avanzadas de clonación. Pero, durante el proceso, el ADN de Ripley se ha mezclado con el de la Reina Alien, por lo que Ripley empieza a desarrollar ciertas características de la peligrosa alienígena.' WHERE pelicula_id = 282;
INSERT INTO PERSONA (nombre) VALUES ('Jean-Pierre Jeunet') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 282, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Jean-Pierre Jeunet' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Sigourney Weaver') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 282, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Sigourney Weaver' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Winona Ryder') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 282, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Winona Ryder' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Dominique Pinon') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 282, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Dominique Pinon' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Ron Perlman') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 282, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Ron Perlman' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Gary Dourdan') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 282, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Gary Dourdan' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Michael Wincott') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 282, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Michael Wincott' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Pepe Arch') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 45, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Pepe Arch' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Ricardo Pérez') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 45, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Ricardo Pérez' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Slobotzky') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 45, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Slobotzky' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('La Kikis') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 45, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'La Kikis' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Susana Zabaleta') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 45, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Susana Zabaleta' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Johann Dionnet') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 133, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Johann Dionnet' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Baptiste Lecaplain') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 133, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Baptiste Lecaplain' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Élisa Erka') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 133, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Élisa Erka' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Romain Francisco') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 133, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Romain Francisco' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Amaury de Crayencour') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 133, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Amaury de Crayencour' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Ariane Mourier') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 133, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Ariane Mourier' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Alison Wheeler') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 133, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Alison Wheeler' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Carla Simón') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 170, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Carla Simón' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Llúcia Garcia') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 170, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Llúcia Garcia' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Mitch') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 170, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Mitch' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Tristán Ulloa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 170, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Tristán Ulloa' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Celine Tyll') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 170, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Celine Tyll' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('León Romagosa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 170, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'León Romagosa' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Hans Romagosa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 170, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Hans Romagosa' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Jason Brown') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 40, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Jason Brown' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Laura Byrne-Cristiano') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 40, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Laura Byrne-Cristiano' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Lori Joffs') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 40, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Lori Joffs' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Ally Kiger') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 40, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Ally Kiger' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Chandler Nash') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 40, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Chandler Nash' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Kaleb Nation') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 40, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Kaleb Nation' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Tori Randall') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 40, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Tori Randall' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Michael Tiddes') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 130, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Michael Tiddes' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Marlon Wayans') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 130, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Marlon Wayans' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Shawn Wayans') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 130, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Shawn Wayans' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Anna Faris') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 130, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Anna Faris' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Regina Hall') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 130, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Regina Hall' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Olivia Rose Keegan') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 130, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Olivia Rose Keegan' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Savannah Lee Nassif') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 130, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Savannah Lee Nassif' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Destin Daniel Cretton') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 138, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Destin Daniel Cretton' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Tom Holland') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 138, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Tom Holland' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Zendaya') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 138, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Zendaya' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Sadie Sink') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 138, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Sadie Sink' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jacob Batalon') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 138, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jacob Batalon' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jon Bernthal') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 138, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jon Bernthal' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Tramell Tillman') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 138, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Tramell Tillman' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Jon Favreau') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 140, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Jon Favreau' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Pedro Pascal') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 140, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Pedro Pascal' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jeremy Allen White') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 140, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jeremy Allen White' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Sigourney Weaver') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 140, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Sigourney Weaver' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Brendan Wayne') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 140, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Brendan Wayne' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Lateef Crowder') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 140, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Lateef Crowder' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Steve Blum') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 140, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Steve Blum' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Craig Gillespie') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 126, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Craig Gillespie' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Milly Alcock') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 126, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Milly Alcock' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Eve Ridley') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 126, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Eve Ridley' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Matthias Schoenaerts') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 126, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Matthias Schoenaerts' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jason Momoa') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 126, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jason Momoa' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('David Krumholtz') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 126, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'David Krumholtz' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Emily Beecham') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 126, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Emily Beecham' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Andrew Stanton') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 125, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Andrew Stanton' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Tom Hanks') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 125, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Tom Hanks' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Tim Allen') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 125, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Tim Allen' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Joan Cusack') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 125, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Joan Cusack' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Greta Lee') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 125, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Greta Lee' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Conan O''Brien') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 125, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Conan O''Brien' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Craig Robinson') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 125, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Craig Robinson' ON CONFLICT DO NOTHING;

UPDATE PELICULA SET sinopsis = 'Precuela de la famosa serie televisiva. La fuente de los impulsos autodestructivos de Laura Palmer está en los abusos que sufre por parte de alguien muy cercano, quien sufre la posesión del diabólico BOB. Cuando Laura se da cuenta de que su mejor amiga, Donna Hayward, se encamina a su mismo sendero autodestructivo, tiene un ataque de lucidez que le permite prevenírselo.' WHERE pelicula_id = 319;
INSERT INTO PERSONA (nombre) VALUES ('David Lynch') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 319, persona_id, 'Director' FROM PERSONA WHERE nombre = 'David Lynch' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Sheryl Lee') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 319, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Sheryl Lee' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Ray Wise') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 319, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Ray Wise' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Mädchen Amick') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 319, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Mädchen Amick' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Dana Ashbrook') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 319, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Dana Ashbrook' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Phoebe Augustine') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 319, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Phoebe Augustine' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('David Bowie') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 319, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'David Bowie' ON CONFLICT DO NOTHING;

INSERT INTO PERSONA (nombre) VALUES ('Paul Andrew Williams') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 132, persona_id, 'Director' FROM PERSONA WHERE nombre = 'Paul Andrew Williams' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Andy Serkis') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 132, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Andy Serkis' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Reece Shearsmith') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 132, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Reece Shearsmith' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Jennifer Ellison') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 132, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Jennifer Ellison' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Steven O''Donnell') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 132, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Steven O''Donnell' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Cat Meacher') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 132, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Cat Meacher' ON CONFLICT DO NOTHING;
INSERT INTO PERSONA (nombre) VALUES ('Danny Nussbaum') ON CONFLICT (nombre) DO NOTHING;
INSERT INTO PELICULA_PERSONA (pelicula_id, persona_id, rol) SELECT 132, persona_id, 'Actor' FROM PERSONA WHERE nombre = 'Danny Nussbaum' ON CONFLICT DO NOTHING;

COMMIT;