import json

with open("cartelera_veracruz_completa.json", "r", encoding="utf-8") as f:
    data = json.load(f)

# The JSON contains an array of functions. Wait, cartelera_veracruz_completa.json is generated by the script.
# The script ONLY outputs what it extracted. It doesn't output the raw GraphQL.
# But earlier I ran `inspect_graphql.py`, which failed.
